version: '3.8'

services:
########## FIRST SERVICE - DATABASE
  db: 
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

########## SECOND SERVICE - API
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - backend:/usr/src/app/

    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

########## THIRD SERVICE - FRONTEND-vue
  frontend:
    build:
      context: ./frontend-vue
    ports:
      - 8080:8080
    volumes:
       - frontend-vue:/app 

######### THIRD SERVICE - FRONTEND-react
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react/src:/app/src
      - ./frontend-react/public:/app/public
      - ./frontend-react/package.json:/app/package.json
      - ./frontend-react/index.html:/app/index.html    

volumes:
  postgres_data:
  backend:
  frontend-vue:
  frontend-react: