version: '3.8'

services:
########## FIRST SERVICE - DATABASE
  eaty-database: 
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

########## SECOND SERVICE - API
  eaty-backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - backend:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - eaty-database

########## THIRD SERVICE - FRONTEND
  eaty-frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    # volumes:
    #   - ./frontend:/app  

volumes:
  postgres_data:
  backend:
  frontend: