# Generated by Django 4.2.1 on 2023-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('food1', models.TextField()),
                ('food2', models.TextField()),
                ('food3', models.TextField()),
                ('food4', models.TextField()),
            ],
        ),
    ]
