# Generated by Django 4.2.1 on 2023-05-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Foods',
        ),
    ]
