# Generated by Django 4.2 on 2023-06-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='name',
            new_name='category',
        ),
    ]
