# Generated by Django 4.2 on 2023-06-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealgenerator', '0002_rename_name_foodcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food',
        ),
    ]
