name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Glad to have you contribute to Eaty."
        pr-message: "Hello! Glad to have you contribute to Eaty. Changes should be pushed to the current Sprint as updated in our Discord Channel"
