name: Build and Push Docker Image
on:
  push:
    branches:
      - "Sprint-3"

jobs:
  build-and-push:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and push api image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eaty-api:${{ github.sha }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./front-react
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eaty-front:${{ github.sha }}


        
    
