# name: Build and Push Docker Image
# on:
#   push:
#     branches:
#       - "Sprint-3"

# jobs:
#   build-and-push:
#     name: Push Docker images to Docker Hub
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#       with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Build and push api image
#       uses: docker/build-push-action@v4
#       with:
#         context: ./backend
#         push: true
#         tags: ${{ secrets.DOCKERHUB_USERNAME }}/eaty-api:${{ github.sha }}

#     - name: Build and push frontend image
#       uses: docker/build-push-action@v4
#       with:
#         context: ./front-react
#         push: true
#         tags: ${{ secrets.DOCKERHUB_USERNAME }}/eaty-front:${{ github.sha }}



name: push to dockerhub ci

on:
  push:
    branches:
      - "Sprint-3"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0

        
    
